
replicaCount: 1

image:
  repository: linuxserver/sonarr
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - sonarr.bananaspliff.org
  tls:
   - secretName: sonarr-bananaspliff-org
     hosts:
       - sonarr.bananaspliff.org

volumes:
  - name: myvolume
    persistentVolumeClaim:
      claimName: myvolume

volumeMounts:
  - name: myvolume
    mountPath: "/config"
    subPath: "configs/sonarr"
  - name: myvolume
    mountPath: "/downloads"
    subPath: "downloads/sonarr"
  - name: myvolume
    mountPath: "/tv"
    subPath: "medias/tv"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
