kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myvolume-{{default "default" .Release.Namespace}}
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage }}
