
replicaCount: 1

image:
  repository: emby/embyserver
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: UID
    value: "1001"
  - name: GID
    value: "100"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - emby.bananaspliff.org
  tls:
   - secretName: emby-bananaspliff-org
     hosts:
       - emby.bananaspliff.org

volumes:
  - name: myvolume
    persistentVolumeClaim:
      claimName: myvolume

volumeMounts:
  - name: myvolume
    mountPath: "/config"
    subPath: "configs/emby"
  - name: myvolume
    mountPath: "/medias"
    subPath: "medias"

resources:
  requests:
    memory: 2048m
    cpu: 1
  limits:
    memory: 4096m
    cpu: 5

nodeSelector: {}

tolerations: []

affinity: {}
