
image:
  repository: atmoz/sftp
  tag: latest
  pullPolicy: IfNotPresent
  args: "foo:foo:1001"

service:
  type: NodePort
  port: 22

volumes:
  - name: myvolume
    persistentVolumeClaim:
      claimName: myvolume

volumeMounts:
  - name: myvolume
    mountPath: "/home/foo"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
