
replicaCount: 1

image:
  repository: linuxserver/jackett
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: PUID
    value: "1001"
  - name: PGID
    value: "100"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - jackett.bananaspliff.org
  tls:
   - secretName: jackett-bananaspliff-org
     hosts:
       - jackett.bananaspliff.org

volumes:
  - name: myvolume
    persistentVolumeClaim:
      claimName: myvolume

volumeMounts:
  - name: myvolume
    mountPath: "/config"
    subPath: "configs/jackett"
  - name: myvolume
    mountPath: "/downloads"
    subPath: "downloads/jackett"

resources:
  requests:
    memory: 128m
    cpu: 0.1
  limits:
    memory: 256m
    cpu: 0.25

nodeSelector: {}

tolerations: []

affinity: {}
