apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "jackett.fullname" . }}
  labels:
    app: {{ template "jackett.name" . }}
    chart: {{ template "jackett.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "jackett.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "jackett.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
      - name: myvolume
        persistentVolumeClaim:
          claimName: myvolume-{{default "default" .Release.Namespace}}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9117
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: myvolume
              mountPath: "/config"
              subPath: "configs/{{ default "jackett" .Values.subDomain }}"
            - name: myvolume
              mountPath: "/downloads"
              subPath: "downloads/{{ default "jackett" .Values.subDomain }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
