{{- if .Values.ingress.enabled -}}
{{- $fullName := include "jackett.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "jackett.name" . }}
    chart: {{ template "jackett.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  tls:
    - hosts:
      - {{ default "jackett" .Values.subDomain }}.{{default "default" .Release.Namespace}}.{{ .Values.domain }}
      secretName: {{ default "jackett" .Values.subDomain }}-{{default "default" .Release.Namespace}}-{{ .Values.domain }}-tls
  rules:
    - host: {{ default "jackett" .Values.subDomain }}.{{default "default" .Release.Namespace}}.{{ .Values.domain }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
{{- end }}
