# Default values for myvolume.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

storageClass: bananaspliff-nfs

storage: 512Gi

# WARNING !!! removing the package causes the physical removal of the volume

